In [5]:
import numpy as npp

In [8]:
z1=npp.zeros(10)
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
z3=npp.full(10,5.0)
z3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
z=npp.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a=npp.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
import numpy as np

el = []
a = np.arange(10, 51, 2)

for i in a:
    if i % 2 == 0:
        el.append(i)

el_arr = np.array(el)
print(el_arr)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [17]:
import numpy as np

a1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
import numpy as np
a2=np.eye(3)
print(a2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
ran_num=np.random.rand()
print(ran_num)

0.9059614742145671


In [20]:
import numpy as np
a=np.random.random(25)
print(a)

[0.11303494 0.21083166 0.85894536 0.76094289 0.62287601 0.54593823
 0.08443257 0.52585116 0.16559961 0.20220198 0.75500069 0.83948053
 0.05018986 0.88587743 0.21239124 0.69429953 0.22225847 0.05285568
 0.91948957 0.02814277 0.11511725 0.33605106 0.67200187 0.44777894
 0.30806331]


In [22]:
import numpy as np

ar = np.arange(0.01, 1.0, 0.01)
print(ar)


[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99]


In [23]:
import numpy as np

la = np.linspace(0,1,20)
print(la)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [25]:
import numpy as np
mat=np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
mat[2:6,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
mat[3:6,4:6]

array([[20],
       [25]])

In [28]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
mat[4:6,0:6]

array([[21, 22, 23, 24, 25]])

In [30]:
mat[3:6,0:6]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
sum1 = np.sum(mat)
sum1

325

In [32]:
sd = np.std(mat)
sd

7.211102550927978

In [33]:
col_sum=np.sum(mat,axis=0)
col_sum

array([55, 60, 65, 70, 75])